### ISSUE TITLE
add coze.com to list

### ISSUE THREAD

**Issue by yangyaohope** [cmliu/ACL4SSR#3]
诉求：让coze.com走代理。

背景：
Coze（扣子）是一个由字节跳动发布的AI聊天机器人构建平台，旨在帮助用户快速创建、调试和优化AI聊天机器人应用程序。 但coze.com无法在中国大陆访问。

Coze (Kouzi) is an AI chatbot development platform released by ByteDance, designed to help users quickly create, debug, and optimize AI chatbot applications. However, coze.com is inaccessible from Mainland China.

**Comment by cmliu** [comment]
在clash里coze.com走的就是漏网之鱼的规则啊, 你漏网之鱼选择节点后coze.com就走代理了的

**Comment by yangyaohope** [comment]
> 在clash里coze.com走的就是漏网之鱼的规则啊, 你漏网之鱼选择节点后coze.com就走代理了的

get 感谢
